Don't modify a frozen object in SSL resolver.
Sometimes it happens that when submitting forms under https://, I get a crash
because WWW::Mechanize::Chain::SSLResolver tries to change its connection
and the connection is frozen:

TypeError: can't modify frozen object
  from /usr/lib/ruby/1.8/net/https.rb:138:in `verify_mode='
  from /usr/lib/ruby/1.8/net/https.rb:138:in `verify_mode='
  from ./lib/www/mechanize/chain/ssl_resolver.rb:20:in `handle'
  from ./lib/www/mechanize/chain.rb:30:in `pass'
  from ./lib/www/mechanize/chain/handler.rb:6:in `handle'
  from ./lib/www/mechanize/chain/connection_resolver.rb:73:in `handle'
  from ./lib/www/mechanize/chain.rb:30:in `pass'
  from ./lib/www/mechanize/chain/handler.rb:6:in `handle'
  from ./lib/www/mechanize/chain/request_resolver.rb:27:in `handle'
  from ./lib/www/mechanize/chain.rb:30:in `pass'
  from ./lib/www/mechanize/chain/handler.rb:6:in `handle'
  from ./lib/www/mechanize/chain/parameter_resolver.rb:18:in `handle'
  from ./lib/www/mechanize/chain.rb:30:in `pass'
  from ./lib/www/mechanize/chain/handler.rb:6:in `handle'
  from ./lib/www/mechanize/chain/uri_resolver.rb:51:in `handle'
  from ./lib/www/mechanize/chain.rb:25:in `handle'
  from ./lib/www/mechanize.rb:434:in `fetch_page'
  from ./lib/www/mechanize.rb:393:in `post_form'
  from ./lib/www/mechanize.rb:325:in `submit'